### ISSUE TITLE
[development] Update CD Category diagram for frontend by ppt file

### ISSUE THREAD

**Issue by VuthyWA** [pnc-virtual-company/2021-G8-V2-PART1#33]

**Comment by ronanpnc** [comment]
![image](https://user-images.githubusercontent.com/67727245/144098357-3b1d8923-ed11-4ff2-8ea0-8482dbd8e827.png)
i don't understand : @VuthyWA what do you emit exactly ?

also category is a compoent ? is it a view or just the card category ?
