### ISSUE TITLE
[DEVELOPMENT] add userIdList to every events on frontend

### ISSUE THREAD

**Issue by sopheasuon** [pnc-virtual-company/2021-G8-V2-PART1#74]
=> to have a list of users that joined the event on each event 

- on mounted of myEvent and Explore event
   1: get all events 
   2: add userIdList(list of user_id) to every events

**Comment by ronanpnc** [comment]
- you should provide direcly to the front :
-    - the list of event reated by  the user
    - the  right structure for the use who joined
